### ISSUE TITLE
Fix required.

### ISSUE THREAD

**Issue by nityanandagohain** [TezpurUniversityRoboticsSociety/TezpurUniversityRoboticsSociety.github.io#10]
![screenshot from 2018-03-25 10-21-58](https://user-images.githubusercontent.com/26831659/37871881-a75e6a5a-3016-11e8-9466-049d5370010d.png)

**Comment by nityanandagohain** [comment]
ping @AdirthaBorgohain

**Comment by AdirthaBorgohain** [comment]
It was working fine for me earlier. I'll look into it.

**Comment by AdirthaBorgohain** [comment]
Is this fixed?

**Comment by nityanandagohain** [comment]
yes @AdirthaBorgohain
